shinobi_host: "10.10.10.10"
shinobi_port: 8080
api_key: "UfUL1AcqYC9OkNDpj2jeESeAkaOPRj"
group_key: "bS1gixfvdu"
monitor_ids:
  - "cedXRBYLBP80"
  - "u3YA9NhAI080"
  - "Fi92SLk9lL80"
  - "CWBp7pbFZO80"
sheet_id: "16co0aMiaJjEoLZr6YYN7ujjSYx9HpVxFwTicY6E2M_c"
credentials_file: "shinobi-sheets-credentials.json"
scopes:
  - "https://spreadsheets.google.com/feeds"
  - "https://www.googleapis.com/auth/drive"
output_dir: "shinobi_output"
update_interval: 60.0
max_retries: 3
retry_backoff_factor: 1.0